# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b20d28754595ab2927f9a2f0bd08804f256b9a433d79c217f86694320034e72cd3e6d54aa84cb71d5fcfb4e6f369ec9e489e5ba3238f124d0b4922929352798f

test:
  secret_key_base: afa748912935e8982cf47226e2dfa041e15bf998c99c115d48649d90356c6968d60be9629654a802d5544073a3cddd21fd5e9e7f0686cd10ea1b6d05d13fe34b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
